package com.espiedra.api.account.service.infrastructure.adapter.output.persistence.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * ENTITY: MovementEntity (R2DBC)
 * <p>
 * DESIGN PATTERNS:
 * - Entity Pattern: Represents database table structure
 * <p>
 * MAPPING:
 * - Table: movement
 * - Primary Key: movement_id (UUID, auto-generated by database via uuid_generate_v4())
 * <p>
 * NOTE: Spring Data R2DBC auto-detects INSERT vs UPDATE:
 * - If movementId is null → INSERT (database generates UUID)
 * - If movementId is not null → UPDATE (though movements are immutable)
 * <p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table("movement")
public class MovementEntity {

    @Id
    @Column("movement_id")
    private UUID movementId;

    @Column("account_number")
    private Long accountNumber;

    @Column("movement_type")
    private String movementType;

    @Column("amount")
    private BigDecimal amount;

    @Column("balance_before")
    private BigDecimal balanceBefore;

    @Column("balance_after")
    private BigDecimal balanceAfter;

    @Column("description")
    private String description;

    @Column("reference")
    private String reference;

    @Column("transaction_id")
    private String transactionId;

    @Column("reversed_movement_id")
    private UUID reversedMovementId;

    @Column("reversed")
    private Boolean reversed;

    @Column("idempotency_key")
    private UUID idempotencyKey;

    @Column("created_at")
    private LocalDateTime createdAt;

    @Column("correlation_id")
    private UUID correlationId;

    @Column("request_id")
    private UUID requestId;
}
