package com.espiedra.api.customer.service.infrastructure.adapter.input.rest;

import com.espiedra.api.customer.service.infrastructure.input.adapter.rest.customer.service.api.HealthApi;
import com.espiedra.api.customer.service.infrastructure.input.adapter.rest.customer.service.models.ComponentHealth;
import com.espiedra.api.customer.service.infrastructure.input.adapter.rest.customer.service.models.HealthResponse;
import com.espiedra.api.customer.service.infrastructure.input.adapter.rest.customer.service.models.HealthResponseComponents;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Health Check REST Controller - Infrastructure Layer
 * <p>
 * Implements HealthApi interface generated by OpenAPI.
 * Provides health check endpoint for monitoring service availability.
 * Checks database connectivity.
 * <p>
 * DESIGN PATTERNS APPLIED:
 * - Health Check Pattern: Monitors service and dependencies health
 */
@Slf4j
@RestController
@RequiredArgsConstructor
public class HealthController implements HealthApi {

    private final DatabaseClient databaseClient;

    /**
     * GET /health.
     * Health check endpoint.
     *
     * @param exchange ServerWebExchange
     * @return Mono<ResponseEntity<HealthResponse>>
     */
    @Override
    public Mono<ResponseEntity<HealthResponse>> healthCheck(ServerWebExchange exchange) {
        log.debug("Health check requested");

        return checkDatabaseHealth()
                .map(dbHealth -> {
                    HealthResponse response = new HealthResponse();
                    response.setStatus(HealthResponse.StatusEnum.UP);
                    response.setTimestamp(OffsetDateTime.now());

                    // Kafka health check (simplified)
                    ComponentHealth kafkaHealth = new ComponentHealth();
                    kafkaHealth.setStatus(ComponentHealth.StatusEnum.UP);
                    Map<String, Object> kafkaDetails = new HashMap<>();
                    kafkaDetails.put("type", "kafka");
                    kafkaHealth.setDetails(kafkaDetails);

                    // Create HealthResponseComponents with ComponentHealth objects
                    HealthResponseComponents components = new HealthResponseComponents();
                    components.setDatabase(dbHealth);
                    components.setKafka(kafkaHealth);
                    response.setComponents(components);

                    log.debug("Health check: UP");
                    return ResponseEntity.ok(response);
                })
                .onErrorResume(error -> {
                    log.error("Health check failed: {}", error.getMessage());

                    HealthResponse response = new HealthResponse();
                    response.setStatus(HealthResponse.StatusEnum.DOWN);
                    response.setTimestamp(OffsetDateTime.now());

                    return Mono.just(ResponseEntity.status(503).body(response));
                });
    }

    /**
     * Check database connectivity.
     *
     * @return Mono<ComponentHealth>
     */
    private Mono<ComponentHealth> checkDatabaseHealth() {
        return databaseClient.sql("SELECT 1")
                .fetch()
                .one()
                .map(result -> {
                    ComponentHealth health = new ComponentHealth();
                    health.setStatus(ComponentHealth.StatusEnum.UP);

                    Map<String, Object> details = new HashMap<>();
                    details.put("database", "PostgresSQL");
                    details.put("connection", "active");
                    health.setDetails(details);

                    return health;
                })
                .onErrorResume(error -> {
                    ComponentHealth health = new ComponentHealth();
                    health.setStatus(ComponentHealth.StatusEnum.DOWN);

                    Map<String, Object> details = new HashMap<>();
                    details.put("error", error.getMessage());
                    health.setDetails(details);

                    return Mono.just(health);
                });
    }
}
